# This Pipeline executes some kind of e2e test by running instructions from the docs
# To not unnecessarily lengthen the running time of the PR pipelines we just run these
# tests after pushing into main. 
name: E2E Source Installation/Example Test

on:
  push:
    branches: [main, debug-e2e]
  workflow_dispatch:

jobs:
  # In general it would be nice to use windows container for testing this,
  # but by now they are not available for windows based github runner
  from_source_mac-windows:
    name: ${{ matrix.os }} - install from source 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, windows-2022]
    steps:
      - uses: actions/checkout@v3

      - name: Setup VM for cifuzz
        uses: ./.github/actions/vm_setup
        with:
          os: ${{ matrix.os }}

      - name: Install cifuzz
        run: make install 

      - name: Run CMake Example (MacOS)
        if: contains(matrix.os, 'macos')
        run: |
          cd examples/cmake
          ~/cifuzz/bin/cifuzz run -v my_fuzz_test 2>&1 | tee fuzzing.log
          cat fuzzing.log | grep "heap buffer overflow"
          cat fuzzing.log | grep "undefined behaviour"
          cat fuzzing.log | grep -E "Findings:\s+2"
        shell: bash

      - name: Run Other Build System Example (MacOS)
        if: contains(matrix.os, 'macos')
        run: |
          cd examples/other
          ~/cifuzz/bin/cifuzz run -v my_fuzz_test 2>&1 | tee fuzzing.log
          cat fuzzing.log | grep "heap buffer overflow"
          cat fuzzing.log | grep "undefined behaviour"
          cat fuzzing.log | grep -E "Findings:\s+2"
        shell: bash

      - name: Run CMake Example (Windows)
        if: contains(matrix.os, 'windows')
        run: |
          cd examples/cmake
          ~/cifuzz/bin/cifuzz run -v my_fuzz_test 2>&1 | tee fuzzing.log
          # we are not testing for the ubsan finding 
          # as we currently do not support ubsan on windows
          cat fuzzing.log | grep "heap buffer overflow"
          cat fuzzing.log | grep -E "Findings:\s+1"
        shell: bash
